# Site settings
title: My Awesome Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome new blog, powered by Jekyll and GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ray-sh.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb # Replace with your twitter username
github_username:  ray-sh # Replace with your github username

# Build settings
markdown: kramdown
theme: minima # Using a default theme for now
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# files yourself under the `include:` key.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
